name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  linux:
    name: 'Linux (JDK 8)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Test'
        run: |
          ./gradlew --no-parallel --no-daemon build -x npmTest
  linux-self:
    name: 'Self-check, Linux (JDK 8)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 10
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Self-check'
        run: |
          ./gradlew --no-parallel --no-daemon jar
          ./gradlew --no-parallel --no-daemon -PautostyleSelf autostyleCheck
