name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# Skip "GitHub Actions" error markers from tests
env:
  AUTOSTYLE_SKIP_GITHUB_ACTIONS: true

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  linux:
    name: 'Linux (JDK 17)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: 'Test'
        run: |
          ./gradlew --no-parallel --no-daemon build -x npmTest -x autostyleFreshmarkCheck
  linux-self:
    name: 'Self-check, Linux (JDK 17)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: 'Self-check'
        run: |
          ./gradlew --no-parallel --no-daemon jar
          ./gradlew --no-parallel --no-daemon -PautostyleSelf autostyleCheck
