name: Regress

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  mac-jmeter:
    name: 'Apache JMeter (JDK 17, MacOS)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: 'Clone Apache JMeter'
        run: |
          git clone --depth 100 https://github.com/apache/jmeter.git ../jmeter
          git rev-parse HEAD
      - name: 'autostyleCheck'
        working-directory: ../jmeter
        run: |
          ./gradlew -no-parallel --no-daemon -PchecksumIgnore -PlocalAutostyle autostyleCheck
      - name: 'autostyleApply'
        working-directory: ../jmeter
        run: |
          ./gradlew -no-parallel --no-daemon -PchecksumIgnore -PlocalAutostyle autostyleApply

  linux-vrp:
    name: 'vlsi-release-plugins (JDK 17, Linux)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: zulu
      - name: 'Clone vlsi-release-plugins'
        run: |
          git clone --depth 100 https://github.com/vlsi/vlsi-release-plugins.git ../vlsi-release-plugins
          git rev-parse HEAD
      - name: 'autostyleCheck'
        working-directory: ../vlsi-release-plugins
        run: |
          ./gradlew -no-parallel --no-daemon -PchecksumIgnore -PlocalAutostyle autostyleCheck
      - name: 'autostyleApply'
        working-directory: ../vlsi-release-plugins
        run: |
          ./gradlew -no-parallel --no-daemon -PchecksumIgnore -PlocalAutostyle autostyleApply
